Update sync-m3u-and-json.yml

diff --git a/.github/workflows/sync-m3u-and-json.yml b/.github/workflows/sync-m3u-and-json.yml
--- a/.github/workflows/sync-m3u-and-json.yml
+++ b/.github/workflows/sync-m3u-and-json.yml
@@ -45,12 +45,12 @@ jobs:
       - name: Fetch source M3U file
         if: steps.check_trigger.outputs.trigger_type == 'schedule_or_manual'
         run: |
-        set -e
-    # 增加--retry 3（重试3次）和--retry-delay 5（每次重试间隔5秒）确保下载成功
-    curl -fL --retry 3 --retry-delay 5 -o iptv.m3u "$M3U_SOURCE_URL"
-    echo "Downloaded iptv.m3u lines:" && wc -l iptv.m3u
-    echo "First 3 lines of iptv.m3u:" && head -n 3 iptv.m3u
-    test -s iptv.m3u || { echo "Error: iptv.m3u is empty or not downloaded after 3 retries"; exit 1; }
+          set -e
+          # 增加--retry 3（重试3次）和--retry-delay 5（每次重试间隔5秒）确保下载成功
+          curl -fL --retry 3 --retry-delay 5 -o iptv.m3u "https://live.ottiptv.cc/iptv.m3u?userid=8257116338&sign=0ee32bfd89ad8fb98abcd834c5bca8a9d2067e9246d1afe59ed28b776baf830aac5a8a3be63250f7b48bff27641ac52755922b1caa12c7d5a7830ed826437d537c6bc26aa6b0d0&auth_token=5fc58b8400b4d34067df90bae9ffe50c"
+          echo "Downloaded iptv.m3u lines:" && wc -l iptv.m3u
+          echo "First 3 lines of iptv.m3u:" && head -n 3 iptv.m3u
+          test -s iptv.m3u || { echo "Error: iptv.m3u is empty or not downloaded after 3 retries"; exit 1; }
     
       - name: Process & generate li.m3u
         if: steps.check_trigger.outputs.trigger_type == 'schedule_or_manual'
